freebsd11_task:
  freebsd_instance:
    image: freebsd-11-2-release-amd64

  install_script:
    #- env ASSUME_ALWAYS_YES=yes
    - pkg update -f
    - pkg upgrade pkg -y
    - pkg install lang/gcc -y
    - pkg install readline -y

  container:
    image: python:latest

  script:
    - python waf configure --include-tests
    # gcc [
    - python waf build_gcc
    - sudo python waf install_gcc
    - pushd build/gcc/lua/lua-5.3.4-tests
    - lua -e"_U=true" all.lua
    - lua all.lua
    - popd
    - sudo python waf uninstall_gcc
    - python waf clean_gcc
    # gcc ]
    # clang [
    - python waf build_clang
    - sudo python waf install_clang
    - pushd build/clang/lua/lua-5.3.4-tests
    - lua -e"_U=true" all.lua
    - lua all.lua
    - popd
    - sudo python waf uninstall_clang
    - python waf clean_clang
    # clang ]
    - python waf distclean
    # including ltests
    - python waf configure --ltests --include-tests
    # gcc [
    - python waf build_gcc
    - sudo python waf install_gcc
    - pushd build/gcc/lua/lua-5.3.4-tests
    - lua -e"_U=true" all.lua
    - lua all.lua
    - popd
    - sudo python waf uninstall_gcc
    - python waf clean_gcc
    # gcc ]
    # clang [
    - python waf build_clang
    - sudo python waf install_clang
    - pushd build/clang/lua/lua-5.3.4-tests
    - lua -e"_U=true" all.lua
    - lua all.lua
    - popd
    - sudo python waf uninstall_clang
    - python waf clean_clang
    # clang ]
    - python waf distclean
