environment:
  LUA: LUA

task:

  matrix:

    - container:
      image: python2.7
      image: python3.7

    - freebsd_instance:
        matrix:
          image: freebsd-12-0-release-amd64
      container:
        image: python:latest

      freebsd_setup_script:
        - echo "freebsd_setup_script"

      freebsd_install_script:
        - echo "freebsd_install_script"

  script:
    - echo "script"