# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

build:
  image: latest

version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip

python:
  version: 3.7
  install:
    - requirements: requirements.txt

conda:
  environment: environment.yml
