[tool.black]
line-length = 88
target_version = ['py37']
include = 'wscript$|.py$'
exclude = '''
(
  /(
      \.git
    | (build)/*
    | (\.)(waf)-(\d{1,}[.]\d{1,}[.]\d{1,})-([0-9a-z]{32})
    | (waf)-(\d{1,}[.]\d{1,}[.]\d{1,})-([0-9a-z]{32})
    | (\.)(waf3)-(\d{1,}[.]\d{1,}[.]\d{1,})-([0-9a-z]{32})
    | (waf3)-(\d{1,}[.]\d{1,}[.]\d{1,})-([0-9a-z]{32})
    | (docs)/(_themes)/*
  )/
)
'''
