.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\all_win.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\api.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\attrib.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\big.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\bitwise.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\calls.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\closure.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\code.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\constructs.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\coroutine.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\db.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\errors.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\events.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\files.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\gc.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\goto.lua.
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\literals.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\locals.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\main.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\main_win.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\math.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\nextvar.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\pm.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\sort.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\strings.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\tpack.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\utf8.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\vararg.lua
.\build\lua\x64\Debug\lua.exe lua\lua-5.3.4-tests\verybig.lua
