#!/usr/bin/env python3
# encoding: utf-8

# SPDX-License-Identifier: MIT


def build(bld):
    """Documentaton build"""
    source = [
        bld.path.find_node("changelog.rst"),
        bld.path.find_node("api.rst"),
        bld.path.find_node("build.rst"),
        bld.path.find_node("ci.rst"),
        bld.path.find_node("contributing.rst"),
        bld.path.find_node("demos.rst"),
        bld.path.find_node("install.rst"),
        bld.path.find_node("license.rst"),
        bld.path.find_node("manual.rst"),
        bld.path.find_node("start.rst"),
        bld.path.find_node("test.rst"),
        bld.path.find_node("index.rst"),
    ]
    bld(features="sphinx", source=source, confpy="conf.py", buildername="html")
    bld(features="doxygen", conf="doxygen.conf")
